name: Email Test Action

on:
  push:
    branches:
      - main  # change this if your default branch is different
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: 23f1002231@ds.study.iitm.ac.in
        run: echo "Hello, world!"
